### ISSUE TITLE
[BUG] some items are not named correctly, different orientations for the incorrect placement positions

### ISSUE THREAD

**Issue by toastedfoxx** [SaltSouls/Packed-Up#12]
**Describe the Bug:**
some names don't show up correctly for blocks, and some blocks when placed face the opposite way of what they were supposed to face when placed down

**Expected Behavior:**
block names to be present, and blocks facing the expected way when placing them down

**Version (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.3.6
 - Mod: 0.2.6

**Screenshots:**
![image](https://github.com/user-attachments/assets/bb1825af-05eb-4302-8427-8e7e6dc8f98c)
![image](https://github.com/user-attachments/assets/c216a03f-f430-4c1f-afc1-17e42746ca6b)

**Comment by SaltSouls** [comment]
Those blocks are like that intentionally. As for the naming problem, I had mentioned that I already know that there are translation issues right now as those blocks got slipped into the last minor update by accident. It was in the change log for the mod. That will be fixed with the next update, which should be coming soon. If you really want it fixed now, you can always download the latest lang file from the github and create a resourcepack to fix it.

**Comment by SaltSouls** [comment]
If you **Really** can't wait and want the actual fix(plus a sneak preview of some new stuff), you can use this preview version of the mod. I'm only uploading it here as it isn't supposed to be released yet, but I know some people don't want to wait.

[packedup-0.5.0-beta.zip](https://github.com/user-attachments/files/16823470/packedup-0.5.0-beta.zip)
